version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - '27017:27017'
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '6379:6379'
    networks:
      - my-network

  nodejs-app:
    build:
      context: .
    container_name: my-nodejs-app
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://mongodb:27017/myapp
      REDIS_HOST: redis
    depends_on:
      - mongodb
      - redis
    networks:
      - my-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: my-nginx
    ports:
      - '80:80'
    depends_on:
      - nodejs-app
    networks:
      - my-network

networks:
  my-network:
