version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - myapp-data:/usr/src/app
