version: '3'
services:
  nodejs-app:
    build:
      context: .
    ports:
      - '3000:3000'

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - '80:80'
    depends_on:
      - nodejs-app
