version: '3'
services:
  nodejs-app:
    build:
      context: .
    ports:
      - '3000:3000'
    networks:
      - my-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - '80:80'
    depends_on:
      - nodejs-app
    networks:
      - my-network

networks:
  my-network:
